services:
  frontend:
    restart: unless-stopped
    image: 'frontend-docker-image'
    container_name: frontend
    depends_on:
      - backend
    ports:
      - '3000:80'
  backend:
    restart: unless-stopped
    image: 'backend-docker-image'
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: 'postgres:10-alpine'
    container_name: db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'