enum authorities {
/*
  add your authorities here. E.g:
*/
  USER_MODIFY = "USER_MODIFY",
  USER_DEACTIVATE = "USER_DEACTIVATE",
  DEFAULT = "DEFAULT",
  SEE_ADMIN_PAGE="SEE_ADMIN_PAGE",
  LIST_ELEMENT_CREATE="LIST_ELEMENT_CREATE",
  LIST_ELEMENT_DELETE="LIST_ELEMENT_DELETE",
  LIST_ELEMENT_MODIFY="LIST_ELEMENT_MODIFY",
}

export default authorities;
