name: Say Hello

on:
  push


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello World!"
  reveal-key:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Key
        run: echo $MY_SECRET
  
