name: Say Hello

on:
  push


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Hello World!"
  reveal-key:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Key
        run: echo $MY_SECRET
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run run.sh
        run: ./run.sh
        
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 2222
          script: echo “Hello World”
